import pyautogui

pyautogui.moveTo(1800,0)
pyautogui.sleep(1)
pyautogui.click()
pyautogui.sleep(2)
pyautogui.moveTo(200,150)
pyautogui.mouseDown()
pyautogui.moveTo(1820,130,duration=0.75)
pyautogui.mouseUp()
pyautogui.sleep(2)
pyautogui.doubleClick()
pyautogui.sleep(0.5)
pyautogui.moveTo(1515,180)
pyautogui.sleep(0.5)
pyautogui.click()
pyautogui.sleep(0.5)
pyautogui.moveTo(27,63)
pyautogui.sleep(0.5)
pyautogui.click()
pyautogui.sleep(0.5)
pyautogui.moveTo(52,17)
pyautogui.sleep(0.5)
pyautogui.click()
pyautogui.sleep(0.5)
pyautogui.moveTo(183,181)
pyautogui.sleep(0.5)
pyautogui.click()
pyautogui.sleep(0.5)
pyautogui.moveTo(62,298)
pyautogui.sleep(0.5)
pyautogui.doubleClick()
pyautogui.sleep(0.5)
pyautogui.moveTo(238,155)
pyautogui.sleep(0.5)
pyautogui.doubleClick()
pyautogui.sleep(0.5)
pyautogui.doubleClick()
pyautogui.sleep(0.5)
pyautogui.moveTo(775,502)
pyautogui.sleep(0.5)
pyautogui.click()
pyautogui.sleep(0.5)
pyautogui.moveTo(575,298)
pyautogui.sleep(0.5)
pyautogui.click()
pyautogui.sleep(0.5)
pyautogui.write("teste.py")
pyautogui.press("enter")
pyautogui.write("print('hello word')")
pyautogui.press("enter")







